### ISSUE TITLE
Squashed PR commit messages cause `InvalidBody` error

### ISSUE THREAD

**Issue by mjhipp** [crate-ci/git-conventional#12]
I ran into this issue when using https://github.com/orhun/git-cliff to create a changelog. 

See: https://github.com/orhun/git-cliff/issues/6

It seems that when squash-merging a PR (with a conventional commit title), with no body message, it causes this error. I am wondering if it is some sort of newline characters being added by GitHub. The commit messages were likely created using the https://github.com/sindresorhus/refined-github extension.

I tried to find the error and it looks like it comes from here, but I am not very familiar with rust so I am not sure:

https://github.com/crate-ci/git-conventional/blob/0bbf8e0e377a0c9db00bcbf1693579639447e897/src/parser.rs#L137-L141

I am wondering if there is any way to relax this, or if the body is empty or just contains white-space to set it to `None`? It seems to be an optional field:

https://github.com/crate-ci/git-conventional/blob/0bbf8e0e377a0c9db00bcbf1693579639447e897/src/parser.rs#L26

Thank you!

**Comment by epage** [comment]
Interesting, this only occurs when there are exactly two newlines

**Comment by epage** [comment]
v0.10.1 is now released with this fixed
