### ISSUE TITLE
InvalidScope error returned if scope contains a number

### ISSUE THREAD

**Issue by rhssk** [crate-ci/git-conventional#14]
Hi,

It appears that if a scope contains a number (or anything else that is not a alphabetical char or a space or a dash), it is rejected as invalid right here:
https://github.com/crate-ci/git-conventional/blob/b9c0e44dc3ed7db2572d7d9d1ae6acf0ca2b1ada/src/parser.rs#L92-L102
https://github.com/crate-ci/git-conventional/blob/b9c0e44dc3ed7db2572d7d9d1ae6acf0ca2b1ada/src/parser.rs#L56-L58

According to spec,
> A scope MUST consist of a noun describing a section of the codebase surrounded by parenthesis

I'm not a native speaker but to me it seems like architectures (e.g. x86), board names (e.g. rpi4) etc. could all fall into the noun category despite containing a number.

Also, if we're being really pedantic, the current checks don't prevent verbs from being used as a scope.

Any thoughts?

**Comment by epage** [comment]
I think those are good examples of nouns that justify expanding the supported characters.

I'm surprised space is allowed.  Not sure what the intention was from the original author (and wish conventional provided an ABNF grammar to clarify these things)

**Comment by epage** [comment]
New version is released.

**Comment by rhssk** [comment]
Thanks!
