### ISSUE TITLE
Underscores / hyphens are not allowed in scopes

### ISSUE THREAD

**Issue by pataar** [crate-ci/git-conventional#17]
Hi! We're using git cliff which has git-conventional as dependency. Currently we use underscores / hyphens to indicate compound nouns as scope. This is not supported by git-conventional while it's fine by the convention: https://github.com/conventional-commits/parser#the-grammar. 

Any chance to allow these characters to be used? 

Thanks in advance!

**Comment by epage** [comment]
Yeah, the spec has a lot of ambuguities in it that make it unclear.  I wish there was an official grammar.  I'll see how it works out syncing up with that grammar.

**Comment by pataar** [comment]
Thank you very much for the fast response and changes!
