### ISSUE TITLE
Allow issue numbers as scope

### ISSUE THREAD

**Issue by sascha-andres** [crate-ci/git-conventional#28]
I'd like to use issue numbers (like `#1`) as scope but according to https://www.conventionalcommits.org/ this is not valid, so this is not a bug report.

Would it be a good addition to add an option to allow everything as a scope?

**Comment by epage** [comment]
For context:

> A scope MAY be provided after a type. A scope MUST consist of a noun describing a section of the codebase surrounded by parenthesis, e.g., fix(parser):

They have also started on a [grammar](https://github.com/conventional-commits/parser).  git-conventional was updated to mostly match the grammar, e.g. see [scope's parser](https://github.com/crate-ci/git-conventional/blob/master/src/parser.rs#L101).

That said, **I would recommend not abusing the fact that we can't validate the semantics of your scope.  The scope is meant to convey a specific type of context that issue numbers do not.**

**Comment by epage** [comment]
Also, if there is a specific problem you've had with having a commit parsed, please open a bug report with the reproduction case
