### ISSUE TITLE
False recognition of non-conventional commits

### ISSUE THREAD

**Issue by thucke** [crate-ci/git-conventional#57]
Hi,

I've filed an issue for git-cliff which uses this library as its functional base (see https://github.com/orhun/git-cliff/issues/548).

The issue I'm experiencing there seem to have its origin in any logic here how conventional commits are recognized. When I use a commit like "JIRA-xxxx: Lorem ipsum" this commit is classified as conventional by your library. Obvioulsy the only criteria to regognize a commit as conventionalmis an existing colon in the header.

I'd like to suggest that a kind of configuration or pattern would be allowed with that types and optionally scopes could be set for valid conventional commits.

Thanks for your support.

**Comment by epage** [comment]
`git-conventional` is a parser for conventional commits.  There isn't anything to configure for whether something should be treated as such.  That is a concern for higher level tools.
